j = 'TACGACGCGCAGACGCGCACCTGTTTCACGTCATTGACGCGCCCGACGCGCCCGGACGCGCGACGCGCACGACGCGCTATGACGCGCACCGCGATTCTCTTGCTGGACGCGCGACGCGCTAAGACGCGCCAAGGTCGACGCGCGTGCAATCGACGCGCTGACGCGCGACGCGCCAATGACGCGCTCCCAGACGCGCGACGCGCGACGCGCGACGCGCTGGCATGACGCGCGGGAGGACGCGCCGTGTCGACGCGCGACGCGCGACGCGCGACGCGCGATGACGCGCTCTATGACGCGCGACGCGCGACGCGCCGACGCGCATTCCAAGACGCGCCCGACGCGCCGACGCGCGACGCGCTTTGACGCGCAAGAGACGCGCGACGCGCGGGACGCGCGACGCGCAGACGCGCAAGACGCGCGACGCGCGACGCGCGACGCGCGACGCGCGACGCGCCCCTTGACGCGCCATGGGAGTCCGGACGCGCACGACGCGCGTGACGCGCGTACGTATGACGCGCGACGCGCTGACGCGCCCGAAGACGCGCATAACATGATGACGCGCCCGACGCGCATACAGACGCGCAGACGCGCAAGACGCGCGACGCGCGACGCGCTAGACGCGCCCGACGCGCACTAGACGCGCAGACGCGCGCGACGCGCTTTAGACGCGCTAGACGCGCTCGGCGACGCGCAGACGCGCAAAGACGCGCGACGCGCTGACGCGCTTACGCGACGCGCATGACGCGCAGACGCGCGTAGACGCGCGCGGACGCGCAGACGCGCGACGCGCGACGCGCGACGCGCGACGCGCGACGCGCGGGGACGCGCTAGACGCGCGACGCGCCGGAAGACGCGCGACGCGCGACGCGCAAGGACGCGCAGCTGTAACCGACGCGCGACGCGCGTAGACGCGCTAGACGCGCGGACGCGCGACGCGCTTCAGACGCGCCGACGCGCAGTAA'
t = 'GACGCGCGA'

def occurrences(a,b):
    start = 0
    res = ''
    while True:
        start = a.find(b, start) + 1
        if start > 0:
            res += str(start) + ' '
        else:
            return res[:-1]


print (occurrences(j, t))
